{
 "title": "Codefresh / Classic Pipelines / Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aggregation_window",
    "label": "Aggregation window",
    "query": "1m, 10m, 30m, 1h, 3h, 6h, 12h, 24h"
   },
   { "name": "percentile", "label": "Percentile", "query": "50, 90, 95" },
   {
    "name": "cf_account_name",
    "label": "Account",
    "query": {
     "query": "label_values(codefresh_classic_build_info,cf_account_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\"},cluster)"
    }
   },
   {
    "name": "k8s_namespace_name",
    "label": "Namespace",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cluster=~\"$cluster\", cf_account_name=~\"$cf_account_name\"},k8s_namespace_name)"
    }
   },
   {
    "name": "cf_classic_runtime_name",
    "label": "Runtime",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_account_name=~\"$cf_account_name\"},cf_classic_runtime_name)"
    }
   },
   {
    "name": "cf_classic_pipeline_name",
    "label": "Pipeline",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cluster=~\"$cluster\", cf_account_name=~\"$cf_account_name\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\"},cf_classic_pipeline_name)"
    }
   },
   {
    "name": "cf_classic_build_phase_final",
    "label": "Build result",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cluster=~\"$cluster\", cf_account_name=~\"$cf_account_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_phase=~\"terminated|succeeded|failed\"},cf_classic_build_phase)"
    }
   },
   {
    "name": "cf_classic_build_volume",
    "label": "Volume",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cluster=~\"$cluster\", cf_account_name=~\"$cf_account_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\"},cf_classic_build_volume)"
    }
   },
   { "name": "pre_step_type", "query": "_internal:pre-step" },
   { "name": "post_step_type", "query": "_internal:post-step" }
  ]
 },
 "panels": [
  { "title": "Total build duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total build duration, p$percentile",
   "type": "timeseries",
   "description": "Total build duration, broken down by phases:\n\n* `preparing`: Build preparation duration. This phase is required to bootstrap the build and is reflected in the Codefresh UI as “Initializing Process.”\n* `running`: Build execution duration.\n* `finalizing`: Build finalization duration. This phase is required to gracefully terminate build execution and is not reflected in the Codefresh UI.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.$percentile,\n    max_over_time(\n        (\n            sum(\n                {__name__=~\"codefresh_classic_build_phase_completion_timestamp(_seconds)*$\", cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_phase=~\"preparing|running|finalizing\"}\n                -\n                {__name__=~\"codefresh_classic_build_phase_start_timestamp(_seconds)*$\", cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_phase=~\"preparing|running|finalizing\"}\n            ) by (cf_classic_build_id, cf_classic_build_phase)\n            * on (cf_classic_build_id) group_left\n            sum(\n                codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_phase=~\"$cf_classic_build_phase_final\", cf_classic_build_volume=~\"$cf_classic_build_volume\"}\n            ) by (cf_classic_build_id)\n        )\n    [$aggregation_window:])\n) by (cf_classic_build_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Build preparation duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Build preparation duration, p$percentile",
   "type": "timeseries",
   "description": "Build preparation duration, broken down by sub-steps.\n\nThese steps are required to bootstrap the build and are reflected in the Codefresh UI as “Initializing Process.”",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.$percentile,\n    max_over_time(\n        (\n            sum(\n                {__name__=~\"codefresh_classic_build_step_completion_timestamp(_seconds)*$\", cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\"}\n                -\n                {__name__=~\"codefresh_classic_build_step_start_timestamp(_seconds)*$\", cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\"}\n            ) by (cf_classic_build_id, cf_classic_build_step_name)\n            * on (cf_classic_build_id, cf_classic_build_step_name)\n            sum(\n                codefresh_classic_build_step_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_step_type=\"$pre_step_type\"}\n            ) by (cf_classic_build_id, cf_classic_build_step_name)\n            * on (cf_classic_build_id) group_left\n            sum(\n                codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_phase=~\"$cf_classic_build_phase_final\", cf_classic_build_volume=~\"$cf_classic_build_volume\"}\n            ) by (cf_classic_build_id)\n        )\n    [$aggregation_window:])\n) by (cf_classic_build_step_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Build finalization duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Build finalization duration, p$percentile",
   "type": "timeseries",
   "description": "Build finalization duration, broken down by sub-steps.\n\nThese steps are required to gracefully terminate build execution and are not reflected in the Codefresh UI.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.$percentile,\n    max_over_time(\n        (\n            sum(\n                {__name__=~\"codefresh_classic_build_step_completion_timestamp(_seconds)*$\", cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\"}\n                -\n                {__name__=~\"codefresh_classic_build_step_start_timestamp(_seconds)*$\", cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\"}\n            ) by (cf_classic_build_id, cf_classic_build_step_name)\n            * on (cf_classic_build_id, cf_classic_build_step_name)\n            sum(\n                codefresh_classic_build_step_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_step_type=\"$post_step_type\"}\n            ) by (cf_classic_build_id, cf_classic_build_step_name)\n            * on (cf_classic_build_id) group_left\n            sum(\n                codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_phase=~\"$cf_classic_build_phase_final\", cf_classic_build_volume=~\"$cf_classic_build_volume\"}\n            ) by (cf_classic_build_id)\n        )\n    [$aggregation_window:])\n) by (cf_classic_build_step_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Build memory utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Build memory utilization, p$percentile",
   "type": "timeseries",
   "description": "Total build (`dind` pod) memory utilization as a percent of requests/limits.\n\nIf utilization is close to 100%, it indicates that the build is using all of its allocated memory, which may lead to performance issues or OOM (Out of Memory) kills.\n\nIf utilization is close to 0%, it indicates that the build is not using much memory, which may suggest over-provisioning.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "quantile(0.$percentile,\n    sum(\n        container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", container=\"dind\"}\n    ) by (pod)\n    /\n    sum(\n        kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", container=\"dind\", resource=\"memory\"}\n    ) by (pod)\n    * on (pod)\n    sum(\n        label_replace(\n            codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_volume=~\"$cf_classic_build_volume\"},\n            \"pod\",\n            \"dind-$1\",\n            \"cf_classic_build_id\",\n            \"(.*)\"\n        )\n    ) by (pod)\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "quantile(0.$percentile,\n    sum(\n        container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", container=\"dind\"}\n    ) by (pod)\n    /\n    sum(\n        kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", container=\"dind\", resource=\"memory\"}\n    ) by (pod)\n    * on (pod)\n    sum(\n        label_replace(\n            codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_volume=~\"$cf_classic_build_volume\"},\n            \"pod\",\n            \"dind-$1\",\n            \"cf_classic_build_id\",\n            \"(.*)\"\n        )\n    ) by (pod)\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  { "title": "Build CPU utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Build CPU utilization, p$percentile",
   "type": "timeseries",
   "description": "Total build (`dind` pod) CPU utilization as a percent of requests/limits.\n\nIf utilization is close to 100%, it indicates that the build is using all of its allocated CPU, which may lead to performance issues.\n\nIf utilization is close to 0%, it indicates that the build is not using much CPU, which may suggest over-provisioning.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "quantile(0.$percentile,\n    sum(\n        rate(\n            container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", container=\"dind\"}\n        [$__rate_interval])\n    ) by (pod)\n    /\n    sum(\n        kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", container=\"dind\", resource=\"cpu\"}\n    ) by (pod)\n    * on (pod)\n    sum(\n        label_replace(\n            codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_volume=~\"$cf_classic_build_volume\"},\n            \"pod\",\n            \"dind-$1\",\n            \"cf_classic_build_id\",\n            \"(.*)\"\n        )\n    ) by (pod)\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "quantile(0.$percentile,\n    sum(\n        rate(\n            container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", container=\"dind\"}\n        [$__rate_interval])\n    ) by (pod)\n    /\n    sum(\n        kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", container=\"dind\", resource=\"cpu\"}\n    ) by (pod)\n    * on (pod)\n    sum(\n        label_replace(\n            codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_volume=~\"$cf_classic_build_volume\"},\n            \"pod\",\n            \"dind-$1\",\n            \"cf_classic_build_id\",\n            \"(.*)\"\n        )\n    ) by (pod)\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  { "title": "Build executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Build concurrency",
   "type": "timeseries",
   "description": "Number of concurrently running builds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(\n    codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_volume=~\"$cf_classic_build_volume\", cf_classic_build_phase!~\"$cf_classic_build_phase_final\"} > 0\n)",
     "legendFormat": "Active builds"
    }
   ]
  },
  {
   "title": "Build results",
   "type": "timeseries",
   "description": "Number of finished builds, broken down by their results.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(\n    codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\", cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\", cf_classic_build_phase=~\"$cf_classic_build_phase_final\", cf_classic_build_volume=~\"$cf_classic_build_volume\"}\n) by (cf_classic_build_phase)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}