{
 "title": "Codefresh / Classic Build / Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_interval", "label": "Min interval", "query": "1s, 5s, 10s, 15s, 30s, 1m" },
   { "name": "codefresh_url", "label": "Codefresh URL", "query": "https://g.codefresh.io" },
   { "name": "no_account", "label": "Admin view", "query": "true,false" },
   {
    "name": "cf_account_name",
    "label": "Account",
    "query": {
     "query": "label_values(codefresh_classic_build_info,cf_account_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cf_account_name=~\"$cf_account_name\"},cluster)"
    }
   },
   {
    "name": "k8s_namespace_name",
    "label": "Namespace",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cluster=~\"$cluster\", cf_account_name=~\"$cf_account_name\"},k8s_namespace_name)"
    }
   },
   {
    "name": "cf_classic_runtime_name",
    "label": "Runtime",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_account_name=~\"$cf_account_name\"},cf_classic_runtime_name)"
    }
   },
   {
    "name": "cf_classic_pipeline_name",
    "label": "Pipeline",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_account_name=~\"$cf_account_name\", cf_classic_runtime_name=~\"$cf_classic_runtime_name\"},cf_classic_pipeline_name)"
    }
   },
   {
    "name": "cf_classic_build_id",
    "label": "Build ID",
    "query": {
     "query": "label_values(codefresh_classic_build_info{cluster=~\"$cluster\", k8s_namespace_name=~\"$k8s_namespace_name\", cf_account_name=~\"$cf_account_name\", cf_classic_pipeline_name=~\"$cf_classic_pipeline_name\"},cf_classic_build_id)"
    }
   },
   { "name": "pre_step_type", "query": "_internal:pre-step" },
   { "name": "post_step_type", "query": "_internal:post-step" }
  ]
 },
 "panels": [
  { "title": "Build overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build info",
   "type": "table",
   "description": "Information about build",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "codefresh_classic_build_info{cf_classic_build_id=\"$cf_classic_build_id\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Preparation duration",
   "type": "table",
   "description": "Build preparation duration, broken down by sub-steps.\n\nThese steps are required to bootstrap the build and are reflected in the Codefresh UI as “Initializing Process.”",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n    sum(\n        (\n            {__name__=~\"codefresh_classic_build_step_completion_timestamp(_seconds)*$\", cf_classic_build_id=\"$cf_classic_build_id\"}\n            -\n            {__name__=~\"codefresh_classic_build_step_start_timestamp(_seconds)*$\", cf_classic_build_id=\"$cf_classic_build_id\"}\n        )\n        or\n        (\n            time()\n            -\n            {__name__=~\"codefresh_classic_build_step_start_timestamp(_seconds)*$\", cf_classic_build_id=\"$cf_classic_build_id\"}\n        )\n    ) by (cf_classic_build_id, cf_classic_build_step_name)\n    * on(cf_classic_build_id, cf_classic_build_step_name)\n    sum(codefresh_classic_build_step_info{cf_classic_build_id=\"$cf_classic_build_id\", cf_classic_build_step_type=~\"$pre_step_type\"} > 0) by (cf_classic_build_id, cf_classic_build_step_name)\n) by (cf_classic_build_step_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalization duration",
   "type": "table",
   "description": "Build finalization duration, broken down by sub-steps.\n\nThese steps are required to gracefully terminate build execution and are not reflected in the Codefresh UI.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n    sum(\n        (\n            {__name__=~\"codefresh_classic_build_step_completion_timestamp(_seconds)*$\", cf_classic_build_id=\"$cf_classic_build_id\"}\n            -\n            {__name__=~\"codefresh_classic_build_step_start_timestamp(_seconds)*$\", cf_classic_build_id=\"$cf_classic_build_id\"}\n        )\n        or\n        (\n            time()\n            -\n            {__name__=~\"codefresh_classic_build_step_start_timestamp(_seconds)*$\", cf_classic_build_id=\"$cf_classic_build_id\"}\n        )\n    ) by (cf_classic_build_id, cf_classic_build_step_name)\n    * on(cf_classic_build_id, cf_classic_build_step_name)\n    sum(codefresh_classic_build_step_info{cf_classic_build_id=\"$cf_classic_build_id\", cf_classic_build_step_type=~\"$post_step_type\"} > 0) by (cf_classic_build_id, cf_classic_build_step_name)\n) by (cf_classic_build_step_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build memory",
   "type": "stat",
   "description": "Memory resources allocated to the build (`dind` pod).",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\", resource=\"memory\"}\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\", resource=\"memory\"}\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Build memory utilization",
   "type": "timeseries",
   "description": "Total build (`dind` pod) memory utilization as a percent of requests/limits.\n\nIf utilization is close to 100%, it indicates that the build is using all of its allocated memory, which may lead to performance issues or OOM (Out of Memory) kills.\n\nIf utilization is close to 0%, it indicates that the build is not using much memory, which may suggest over-provisioning.",
   "gridPos": { "h": 10, "w": 7, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\"}\n)\n/\nsum(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\", resource=\"memory\"}\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\"}\n)\n/\nsum(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\", resource=\"memory\"}\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Build CPU utilization",
   "type": "timeseries",
   "description": "Total build (`dind` pod) CPU utilization as a percent of requests/limits.\n\nIf utilization is close to 100%, it indicates that the build is using all of its allocated CPU, which may lead to performance issues.\n\nIf utilization is close to 0%, it indicates that the build is not using much CPU, which may suggest over-provisioning.",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\"}\n    [$__rate_interval])\n)\n/\nsum(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\", resource=\"cpu\"}\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\"}\n    [$__rate_interval])\n)\n/\nsum(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\", resource=\"cpu\"}\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Build CPU throttling",
   "type": "timeseries",
   "description": "Share of throttled CPU periods for the build (`dind` pod) as a percent of the total CPU periods.\n\nIf the value is above 0, it indicates that the build is being throttled due to CPU limits set on the `dind` pod. This can lead to slower build times and should be monitored to ensure that the pod has sufficient CPU resources.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    irate(\n        container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", image!=\"\", container!=\"\"}\n    [$__rate_interval])\n    /\n    irate(\n        container_cpu_cfs_periods_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", image!=\"\", container!=\"\"}\n    [$__rate_interval])\n) by (container)\n",
     "legendFormat": "Throttled periods"
    }
   ]
  },
  {
   "title": "Build CPU",
   "type": "stat",
   "description": "CPU resources allocated to the build (`dind` pod).",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\", resource=\"cpu\"}\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container!=\"\", resource=\"cpu\"}\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Storage utilization",
   "type": "timeseries",
   "description": "Total build (attached volume) storage utilization.\n\nIf utilization is at 80%, in-DinD cleaner may be triggered (configurable, [docs](https://artifacthub.io/packages/helm/codefresh-runner/cf-runtime#volume-cleaners)).\n\nIf it's close to 100%, the build may fail because of Out Of Storage.\n\nIf utilization is close to 0%, it indicates that the build is not using much storage, which may suggest over-provisioning.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "docker_volume_kb_total{pod=\"dind-$cf_classic_build_id\"}\n",
     "legendFormat": "Total"
    },
    {
     "expr": "(\n    docker_volume_kb_total{pod=\"dind-$cf_classic_build_id\"}\n    -\n    docker_volume_kb_available{pod=\"dind-$cf_classic_build_id\"}\n)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Inodes utilization",
   "type": "timeseries",
   "description": "Total build (attached volume) index nodes utilization.\n\nIf utilization is at 80%, in-DinD cleaner may be triggered (configurable, [docs](https://artifacthub.io/packages/helm/codefresh-runner/cf-runtime#volume-cleaners)).\n\nIf it's close to 100%, the build may fail because of Out Of Storage.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    docker_volume_inodes_total{pod=\"dind-$cf_classic_build_id\"}\n    -\n    docker_volume_inodes_available{pod=\"dind-$cf_classic_build_id\"}\n)\n/\ndocker_volume_inodes_total{pod=\"dind-$cf_classic_build_id\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Steps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Steps timeline",
   "type": "state-timeline",
   "description": "Step names are displayed as defined in the pipeline YAML.\n\nEach step is clickable, allowing you to navigate directly to the corresponding step in Codefresh.\n\nDuration of the steps is shown with $min_interval precision, which is controlled by “Min interval” variable.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(\n    (codefresh_classic_build_step_info{cf_classic_build_id=\"$cf_classic_build_id\", cf_classic_build_step_phase=~\"preparing|running|finalizing\", cf_classic_build_step_name=~\"[^.]+\", cf_classic_build_step_type!~\"$pre_step_type|$post_step_type\"} > 0)\n) by (cf_classic_build_step_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Steps duration",
   "type": "table",
   "description": "Step durations, broken down by phases:\n\n* `preparing`: Internal preparation time before the actual step begins.\n* `running`: Time taken to execute the step.\n* `finalizing`: Time spent on internal finalization after the step is executed.\n\nStep names are displayed as defined in the pipeline YAML.\n\nEach step is clickable, allowing you to navigate directly to the corresponding step in Codefresh.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n    (\n        {__name__=~\"codefresh_classic_build_step_phase_completion_timestamp(_seconds)*$\", cf_classic_build_id=\"$cf_classic_build_id\", cf_classic_build_step_name=~\"[^.]+\"}\n        -\n        {__name__=~\"codefresh_classic_build_step_phase_start_timestamp(_seconds)*$\", cf_classic_build_id=\"$cf_classic_build_id\", cf_classic_build_step_name=~\"[^.]+\"}\n    )\n    or\n    (\n        time()\n        -\n        {__name__=~\"codefresh_classic_build_step_phase_start_timestamp(_seconds)*$\", cf_classic_build_id=\"$cf_classic_build_id\", cf_classic_build_step_name=~\"[^.]+\"}\n    )\n) by (cf_classic_build_step_name, cf_classic_build_step_phase)",
     "legendFormat": "{{cf_classic_build_step_name}}: {{cf_classic_build_step_phase}}"
    }
   ]
  },
  {
   "title": "Steps memory",
   "type": "timeseries",
   "description": "Memory consumption broken down by step, stacked.\n\nStep names are displayed as defined in the pipeline YAML.\n\nEach step is clickable, allowing you to navigate directly to the corresponding step in Codefresh.\n\n“Build pod memory” is the total memory used by the `dind` pod, which includes the memory used by the Docker daemon itself and any step containers running inside it.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    {__name__=~\"codefresh_classic_build_step_memory_working_set(_bytes)*$\", cf_classic_build_id=\"$cf_classic_build_id\", cf_classic_build_step_name=~\"[^.]+\"}\n) by (cf_classic_build_step_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container=\"dind\"}\n)",
     "legendFormat": "Build pod memory"
    }
   ]
  },
  {
   "title": "Steps CPU",
   "type": "timeseries",
   "description": "CPU consumption broken down by step, stacked.\n\nStep names are displayed as defined in the pipeline YAML.\n\nEach step is clickable, allowing you to navigate directly to the corresponding step in Codefresh.\n\n“Build pod CPU” is the total CPU used by the `dind` pod, which includes the CPU used by the Docker daemon itself and any step containers running inside it.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        {__name__=~\"codefresh_classic_build_step_cpu_time(_seconds)*(_total)*$\",cf_classic_build_id=\"$cf_classic_build_id\", cf_classic_build_step_name=~\"[^.]+\"}\n    [$__rate_interval])\n) by (cf_classic_build_step_name)",
     "legendFormat": "{{cf_classic_build_step_name}}"
    },
    {
     "expr": "rate(\n    container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"dind-${cf_classic_build_id}\", container=\"dind\"}\n[$__rate_interval])",
     "legendFormat": "Build pod CPU"
    }
   ]
  },
  { "title": "Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Engine memory",
   "type": "stat",
   "description": "Memory resources allocated to the `engine` pod.",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\", resource=\"memory\"}\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\", resource=\"memory\"}\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Engine memory utilization",
   "type": "timeseries",
   "description": "Total `engine` pod memory utilization as a percent of requests/limits.\n\nThe `engine` is responsible for steps orchestration and execution.\n\nIf utilization is close to 100%, it indicates that the `engine` pod is using all of its allocated memory, which may lead to performance issues or OOM (Out of Memory) kills.\n\nIf utilization is close to 0%, it indicates that the `engine` pod is not using much memory, which may suggest over-provisioning.",
   "gridPos": { "h": 10, "w": 7, "x": 2, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\"}\n)\n/\nsum(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\", resource=\"memory\"}\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\"}\n)\n/\nsum(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\", resource=\"memory\"}\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Engine CPU utilization",
   "type": "timeseries",
   "description": "Total `engine` pod CPU utilization as a percent of requests/limits.\n\nThe `engine` is responsible for steps orchestration and execution.\n\nIf utilization is close to 100%, it indicates that the `engine` pod is using all of its allocated CPU, which may lead to performance issues.\n\nIf utilization is close to 0%, it indicates that the `engine` pod is not using much CPU, which may suggest over-provisioning.",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\"}\n    [$__rate_interval])\n)\n/\nsum(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\", resource=\"cpu\"}\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\"}\n    [$__rate_interval])\n)\n/\nsum(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\", resource=\"cpu\"}\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Engine CPU throttling",
   "type": "timeseries",
   "description": "Share of throttled CPU periods for the `engine` pod as a percent of the total CPU periods.\n\nIf the value is above 0, it indicates that the `engine` pod is being throttled due to CPU limits set on the pod. This can lead to slower build times and should be monitored to ensure that the pod has sufficient CPU resources.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    irate(\n        container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", image!=\"\", container!=\"\"}\n    [$__rate_interval])\n    /\n    irate(\n        container_cpu_cfs_periods_total{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", image!=\"\", container!=\"\"}\n    [$__rate_interval])\n) by (container)\n",
     "legendFormat": "Throttled periods"
    }
   ]
  },
  {
   "title": "Build CPU",
   "type": "stat",
   "description": "CPU resources allocated to the `engine` pod.",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\", resource=\"cpu\"}\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$k8s_namespace_name\", pod=\"engine-${cf_classic_build_id}\", container!=\"\", resource=\"cpu\"}\n)",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}